// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
