// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :one
INSERT INTO
  users (id, user_name, password_hash)
VALUES
  ($1, $2, $3) RETURNING id, user_name, password_hash, created_at, updated_at
`

type AddUserParams struct {
	ID           uuid.UUID `json:"id"`
	UserName     string    `json:"user_name"`
	PasswordHash []byte    `json:"password_hash"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRow(ctx, addUser, arg.ID, arg.UserName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
